import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TheHeader from '../../components/TheHeader'
import TheFooter from '../../components/TheFooter'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-slate-200">
        <TheHeader />
        <main className=''>{children}</main>
        <TheFooter />
      </body>
    </html>
  )
}
